[2025-04-23T01:43:56.790+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T00:50:00+00:00 [queued]>
[2025-04-23T01:43:56.822+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T00:50:00+00:00 [queued]>
[2025-04-23T01:43:56.824+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 2
[2025-04-23T01:43:56.952+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_kafka_consumer> on 2025-04-23 00:50:00+00:00
[2025-04-23T01:43:56.969+0000] {standard_task_runner.py:60} INFO - Started process 222 to run task
[2025-04-23T01:43:56.982+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mbta_kafka_consumer_dag', 'run_kafka_consumer', 'scheduled__2025-04-23T00:50:00+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/mbta_kafka_consumer_dag.py', '--cfg-path', '/tmp/tmpgpyezmaz']
[2025-04-23T01:43:56.988+0000] {standard_task_runner.py:88} INFO - Job 323: Subtask run_kafka_consumer
[2025-04-23T01:43:57.354+0000] {task_command.py:423} INFO - Running <TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T00:50:00+00:00 [running]> on host f6fee51db313
[2025-04-23T01:43:57.900+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mbta_kafka_consumer_dag' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:50:00+00:00'
[2025-04-23T01:43:57.913+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.9.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-23T01:43:57.922+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T01:44:00.898+0000] {mbta_kafka_consumer.py:51} INFO - âœ… Connected to Snowflake successfully.
[2025-04-23T01:44:00.904+0000] {mbta_kafka_consumer.py:261} INFO - ðŸš€ Starting MBTA Kafka Consumer...
[2025-04-23T01:44:00.923+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-04-23T01:44:00.973+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-04-23T01:44:00.974+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-04-23T01:44:00.977+0000] {consumer.py:119} WARNING - group_id is None: disabling auto-commit.
[2025-04-23T01:44:00.983+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('mbta_alerts', 'mbta_routes', 'mbta_stops', 'mbta_vehicles', 'mbta_predictions', 'mbta_schedules', 'mbta_lines', 'mbta_facilities')
[2025-04-23T01:44:01.008+0000] {cluster.py:317} ERROR - Topic mbta_alerts not found in cluster metadata
[2025-04-23T01:44:01.010+0000] {cluster.py:317} ERROR - Topic mbta_facilities not found in cluster metadata
[2025-04-23T01:44:01.014+0000] {cluster.py:317} ERROR - Topic mbta_predictions not found in cluster metadata
[2025-04-23T01:44:01.015+0000] {cluster.py:317} ERROR - Topic mbta_lines not found in cluster metadata
[2025-04-23T01:44:01.017+0000] {cluster.py:317} ERROR - Topic mbta_schedules not found in cluster metadata
[2025-04-23T01:44:01.018+0000] {cluster.py:317} ERROR - Topic mbta_routes not found in cluster metadata
[2025-04-23T01:44:01.018+0000] {cluster.py:317} ERROR - Topic mbta_vehicles not found in cluster metadata
[2025-04-23T01:44:01.020+0000] {cluster.py:317} ERROR - Topic mbta_stops not found in cluster metadata
[2025-04-23T01:44:01.021+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-04-23T01:44:06.007+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-04-23T01:44:06.036+0000] {connection.py:718} INFO - closed
[2025-04-23T01:44:06.259+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-04-23T01:44:06.419+0000] {mbta_kafka_consumer.py:282} INFO - âœ… Snowflake Connection Closed.
[2025-04-23T01:44:06.423+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-23T01:44:06.484+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mbta_kafka_consumer_dag, task_id=run_kafka_consumer, execution_date=20250423T005000, start_date=20250423T014356, end_date=20250423T014406
[2025-04-23T01:44:06.612+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-23T01:44:06.742+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
